[workspace]
members = ["lambdas/*", "tracing_handler"]

[workspace.package]
name = "oxidar-lambdas"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
lambda_runtime = { version = "0.13.0", features = ["opentelemetry"] }
redis = "0.28.2"
serde = "1"
tokio = { version = "1", features = ["macros"] }
reqwest = "0.12.12"
thiserror = "2.0"
tracing_handler = { path = "./tracing_handler" }
