[workspace]
members = ["lambdas/*", "tracing_handler", "http"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
lambda_runtime = { version = "0.13.0", features = ["opentelemetry"] }
lambda_http = "0.14.0"
envy = "0.4.2"
redis = { version = "0.29", features = ["tls-rustls", "connection-manager", "tokio-rustls-comp"] }
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["macros"] }
reqwest = { version = "0.12.12", default-features = false, features=["rustls-tls"] }
thiserror = "2.0"
tracing_handler = { path = "./tracing_handler" }
http = { path = "./http" }
rustls = { version = "0.23", features = ["ring"] }

