[package]
name = "add_path"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
redis = { workspace = true }
tracing_handler = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
http = { workspace = true }
envy = { workspace = true }

[package.metadata.lambda.env]
REDIS_URL = "redis://127.0.0.1"
